#pragma once

#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 640

#define TEX_PLAYER_WIDTH  288
#define TEX_PLAYER_HEIGHT 48
#define TEX_PLAYER_ROW    1
#define TEX_PLAYER_COLUMN 6

#define PLAYER_WIDTH  48
#define PLAYER_HEIGHT 48

